#!/bin/bash
#add MA Service script, creat link file
#
path="/etc/systemd/system/"
if [[ -f ${path}fibo_config.service   &&  -f ${path}fibo_flash.service  &&   -f ${path}fibo_helper.service ]];then
systemctl enable  fibo_config.service  fibo_flash.service fibo_helper.service
systemctl start  fibo_helper.service fibo_config.service  fibo_flash.service
#VID:PID List
OEMUSBID_LIST=(2cb7:01a2 2cb7:0301 413c:8209 413c:8211 413c:8213 413c:8215)
PROJECT_VID_LIST="2cb7"

#ARRY=($OEMUSBID_LIST)

for s in ${OEMUSBID_LIST[@]}
do
ln -sf   /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/${PROJECT_VID_LIST} /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/$s 
done
chown -R root:root  /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d
chmod 755 -R /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d
fi
