#!/bin/bash
#remove vid:pid link file befor packge remove
rm -rf /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/*:*
path="/etc/systemd/system/"
#stop service
if [[ -f ${path}fibo_config.service && -f ${path}fibo_flash.service && -f ${path}fibo_helper.service && -f ${path}fibo_helper_mbim.service ]];then
    systemctl stop fibo_config.service fibo_flash.service fibo_helper.service fibo_helper_mbim.service
fi
