#!/bin/bash

#not first insatll need stop service first
path="/lib/systemd/system/"
if [[ -f ${path}fibo_config.service   &&  -f ${path}fibo_flash.service  &&   -f ${path}fibo_helper.service && -f ${path}fibo_helper_mbim.service ]];then
  systemctl stop fibo_config.service fibo_flash.service fibo_helper.service fibo_helper_mbim.service
fi
flash_srv_path="/opt/fibocom/fibo_flash_service/FwFlashSrv"

if [[ -f ${flash_srv_path} ]]; then
    rm -rf ${flash_srv_path}
fi